// layout.tsx or layout.jsx

import "./globals.css";
import { DM_Sans } from "next/font/google";
import type { Metadata } from "next";
import Navbar from "./(shared_tsx)/Navbar";
import Footer from "./(shared_tsx)/Footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // use only normal styles
  style: "normal", // explicitly ensure it's not italic
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} font-sans antialiased`}>
        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
